#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Mar 31, 2019 01:32:15 PM CAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import busBoyPrototype_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    busBoyPrototype_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    busBoyPrototype_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+428+108")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.0, rely=0.0, relheight=1.011, relwidth=0.792)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief="groove")
        self.TFrame1.configure(width=475)

        self.table1 = ttk.Button(self.TFrame1)
        self.table1.place(relx=0.063, rely=0.066, height=85, width=86)
        self.table1.configure(takefocus="")
        self.table1.configure(text='''1''')
        self.table1.configure(width=86)

        self.table3 = ttk.Button(self.TFrame1)
        self.table3.place(relx=0.695, rely=0.066, height=85, width=86)
        self.table3.configure(takefocus="")
        self.table3.configure(text='''3''')
        self.table3.configure(width=86)

        self.table2 = ttk.Button(self.TFrame1)
        self.table2.place(relx=0.379, rely=0.066, height=85, width=86)
        self.table2.configure(takefocus="")
        self.table2.configure(text='''2''')
        self.table2.configure(width=86)

        self.TFrame2 = ttk.Frame(top)
        self.TFrame2.place(relx=0.783, rely=0.0, relheight=1.011, relwidth=0.242)

        self.TFrame2.configure(relief='groove')
        self.TFrame2.configure(borderwidth="2")
        self.TFrame2.configure(relief="groove")
        self.TFrame2.configure(width=145)

if __name__ == '__main__':
    vp_start_gui()





